# Generated by Django 2.2.2 on 2019-06-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snapp.Person')),
                ('salary', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
            ],
            bases=('snapp.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snapp.Person')),
                ('salary', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
            ],
            bases=('snapp.person',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snapp.Person')),
                ('passenger_id', models.IntegerField()),
                ('selected_addresses', models.CharField(max_length=200)),
            ],
            bases=('snapp.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
